version: '3'

services:
    db:
        image: postgres:13-alpine
        ports:
            - 61949:5432
        environment:
            POSTGRES_DB: doctrine_test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: s3cr37
